framework:
    command:
        http:
            cluster:
                watch:
                    interval: 1

                    directories:
                        - '%project.directory%/templates'

                    extensions: ['php', 'yaml', 'twig']

    middleware:
        compression: false
        access-log:
            logger: monolog.logger.http

