framework:
    command:
        http:
            cluster:
                watch:
                    interval: 1

                    directories:
                        - '%project%/templates'

                    extensions: ['php', 'yaml', 'twig']

    middleware:
        compression: false
