http:
    logger: monolog.logger.http

    server:
        sockets:
            -
                host: 127.0.0.1
                port: 8080
                bind:
                    reuse-port: true
